"""empty message

Revision ID: 40f6db10b159
Revises: e6105f2d2b92
Create Date: 2024-08-25 09:41:42.874253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f6db10b159'
down_revision: Union[str, None] = 'e6105f2d2b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
