"""empty message

Revision ID: a1e60a73f301
Revises: 40f6db10b159
Create Date: 2024-08-25 09:43:56.633817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e60a73f301'
down_revision: Union[str, None] = '40f6db10b159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'new_type')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('new_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
