"""empty message

Revision ID: b8577818c5c8
Revises: dfe186f874d8
Create Date: 2024-08-25 09:36:23.200318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8577818c5c8'
down_revision: Union[str, None] = 'dfe186f874d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('new_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'new_type')
    # ### end Alembic commands ###
