"""empty message

Revision ID: d5fea30aefca
Revises: cd74b368748c
Create Date: 2024-08-26 09:25:48.099370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fea30aefca'
down_revision: Union[str, None] = 'cd74b368748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=False))
    op.add_column('products', sa.Column('thumbnail', sa.String(), nullable=False))
    op.add_column('products', sa.Column('images', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('products', sa.Column('is_published', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('products', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_published')
    op.drop_column('products', 'images')
    op.drop_column('products', 'thumbnail')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
