"""empty message

Revision ID: f31cf30f761d
Revises: 0df7cee461a7
Create Date: 2024-08-26 09:43:22.156622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31cf30f761d'
down_revision: Union[str, None] = '0df7cee461a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cart_items', ['id'])
    op.create_unique_constraint(None, 'carts', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'carts', type_='unique')
    op.drop_constraint(None, 'cart_items', type_='unique')
    # ### end Alembic commands ###
